version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: placeholder_username
      POSTGRES_PASSWORD: placeholder_password
      POSTGRES_DB: placeholder_db
    ports:
      - "7432:5432"  
    networks:
      - backend_network
      
  backend:
    image: mariebaude/mpmt_back:v1.0
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/placeholder_db
      DATABASE_USERNAME: placeholder_username
      DATABASE_PASSWORD: placeholder_password
      GMAIL_USERNAME: 
      GMAIL_PASSWORD: 
    ports:
      - "8080:8080"
    networks:
      - backend_network  
    depends_on:
      - db
    

  frontend:
    image : mariebaude/mpmt_front:v1.0
    ports:
      - "7085:80" 
    depends_on:
      - backend  

networks:
  backend_network:
    driver: bridge
